
BattleCardOffsetSumary = {
[1] = {src = ccp(0,0),dst = ccp(6,45),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 火箭
[2] = {src = ccp(-6,50),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 火攻
[3] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 突袭
[4] = {src = ccp(0,60),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 蛊惑
[5] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 疗伤
[6] = {src = ccp(0,0),dst = ccp(0,40),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 伏兵
[7] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 铁骑突袭
[8] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 天雷闪
[9] = {src = ccp(0,60),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 长枪突刺
[10] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 坚守
[11] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 铁壁
[12] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 刺甲
[13] = {src = ccp(5,60),dst = ccp(0,-7),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 奔流
[14] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 绊马索
[15] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 剧毒之箭
[16] = {src = ccp(0,0),dst = ccp(10,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 回天术
[17] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 援护
[18] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 笼络
[19] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 燃烧箭
[20] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 突刺
[21] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 锁魂链
[22] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 拜将封侯
[23] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 将计就计
[24] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 火箭连射
[25] = {src = ccp(470,-40),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 擒贼擒王
[26] = {src = ccp(10,20),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 驱虎吞狼
[27] = {src = ccp(10,20),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 美人计.乱
[28] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 奇谋.言毒
[29] = {src = ccp(0,70),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 陷阵冲锋
[30] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 忠心护主
[31] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 大杀四方
[32] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 恶来之力
[33] = {src = ccp(0,0),dst = ccp(0,110),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 五雷轰顶
[34] = {src = ccp(0,60),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 毒箭
[35] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 十面埋伏
[36] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 死守
[37] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 伪报
[38] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 烧粮
[39] = {src = ccp(475,190),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 义胆仁心
[40] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 天罡之气
[41] = {src = ccp(0,200),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 燕人咆哮
[42] = {src = ccp(-10,70),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 无影绝枪
[43] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 奇门遁甲
[44] = {src = ccp(0,60),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 百步穿杨
[45] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 无坚不摧
[46] = {src = ccp(0,200),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 惊涛骇浪
[47] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 勇冠三军
[48] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 心如止水
[49] = {src = ccp(0,170),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = true },-- 飞鸿踏雪
[50] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 横扫千军
[51] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 盾阵
[52] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 反噬
[53] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 怒骂
[54] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 忍辱负重
[55] = {src = ccp(0,20),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 停战协议
[56] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 力断千斤
[57] = {src = ccp(0,45),dst = ccp(0,-45),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 鹰击长空
[58] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 星火燎原
[59] = {src = ccp(0,-10),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 阵前挑战
[60] = {src = ccp(0,90),dst = ccp(0,-80),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 韬光养晦
[61] = {src = ccp(0,50),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 单打独斗
[62] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 不屈意志
[63] = {src = ccp(0,35),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 避实击虚
[64] = {src = ccp(10,100),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 火烧连营
[65] = {src = ccp(0,30),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 卧薪尝胆
[66] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 横扫八荒
[67] = {src = ccp(0,0),dst = ccp(10,100),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 妙手回春
[68] = {src = ccp(0,5),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 黄天当立
[69] = {src = ccp(0,0),dst = ccp(0,30),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 四世三公
[70] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 呼风唤雨
[71] = {src = ccp(0,0),dst = ccp(0,50),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 万箭齐发
[72] = {src = ccp(0,0),dst = ccp(10,90),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 力劈山河
[73] = {src = ccp(0,70),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 太平要术
[74] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 滚石
[75] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 雷击
[76] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 风花雪月
[77] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 横行霸道
[78] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 天降甘霖
[79] = {src = ccp(0,0),dst = ccp(0,0),src_unit_duration = 67,dst_unit_duration = 67,src_flip_y = false,dst_flip_y = false },-- 嗜血成性


}