EventType = enum({"RECONNETING","RECONNECT_FAILED","RECONNECT_SUCCESS",
"PLAYER_UPDATE","DISCOUNT_BUY_LIMIT","FORCE_OFFLINE","LOGIN_RESULT", 
"UPDATE_LEADSHIP","UPDATE_TIP","PLAYER_LEVEL_UP","HOME_UPDATE",
"CLIENT_VERSION_CHANGED","TALENT_BANK", "BOSS_UPDATE", 
"LOADING_TIMEOUT"
})
